name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
          docker build -t quran-app:latest .

          #push the image to docker hub.
          docker login
          docker pull quran-app/yoyo7sniper97/quran-app:latest
          
          docker-compose up 
